//let numero = parseFloat(prompt("Dame un numero"));

//let numero2 = parseFloat(prompt("Dame un numero"));

//console.log( typeof (numero + numero2));

//document.write(numero + numero2);

let numeros = [3,"Angel",6,7,"¿Qué será'"]

//Los arrays tienen un indice y comienza en 0

for (let i = 0; i < numeros.length; i++) {

    console.log(numeros[i]);

    document.write(numeros[i]+ "<br>");
}

let variables =true;
if (variables) {
    document.write (variables);

 if (variables) {
        document.write ("Mi variable es real");
 } else {
        document.write ("Mi variable es falsa");
    
    
    
}

//El ciclo for es un bucle 
//El scope es un alcance de variables solo funcionales al abrir y cerrar llaves    